sudo: required

services:
  - docker

language: generic

env:
- DESKTOP=xfce
- DESKTOP=icewm

script:
  - docker build -t local/ubuntu-${DESKTOP}-vnc -f ./Dockerfile.ubuntu.${DESKTOP}.vnc .
after_success:
  - bash .build/trigger_dockerhub.sh ubuntu-${DESKTOP}-vnc
